Update makefile to install/remove icons and desktop entry
aristocratos/btop pull request #329
Opened 2022-05-07 12:02 UTC by yonatan8070

2022-05-07 17:42 UTC, aristocratos requested changes

2022-05-07 18:09 UTC, yonatan8070 commented on Makefile
> +ICONDIR ?= /usr/share/icons/hicolor
The reason I did it this way is because `PREFIX` and `DESTDIR` pointed to `/usr/local`, and on my system (Arch) there wasn't an `applications` directory in `/usr/local/share`, same goes for icons. 

How could it be made to work with things that go into `/usr/share`? Could we simply make `/usr/local/share/applications` and the system would recognize it?

2022-05-07 18:41 UTC, aristocratos commented on Makefile
> +ICONDIR ?= /usr/share/icons/hicolor
@yonatan8070 
That shouldn't be an issue, from https://wiki.archlinux.org/title/desktop_entries:
> Desktop entries for applications, or .desktop files, are generally a combination of meta information resources and a shortcut of an application. These files usually reside in /usr/share/applications/ or /usr/local/share/applications/ for applications installed system-wide, or ~/.local/share/applications/ for user-specific applications. User entries take precedence over system entries. 

Hardcoding the path to a superuser owned directory would mean the installation would fail if a normal user is trying to install to home directory.

2022-05-07 18:45 UTC, yonatan8070 commented on Makefile
> +ICONDIR ?= /usr/share/icons/hicolor
That makes sense, I'm not at my PC right now, I might have time later, if not I'll do it tomorrow.

2022-05-08 11:38 UTC, yonatan8070 commented on Makefile
> +ICONDIR ?= /usr/share/icons/hicolor
Pushed changes to the Makefile, should now install to the correct location

2022-05-08 12:03 UTC, aristocratos approved these changes
Awesome, thanks for contributing!

2022-05-08 12:03 UTC, merged

2022-05-08 12:04 UTC, yonatan8070 commented
You're welcome!