Proper kernel process filtering.
aristocratos/btop pull request #337
Opened 2022-05-20 20:41 UTC by 0xJoeMama

Properly add the functionality mentioned in #332.

2022-05-20 20:55 UTC, 0xJoeMama commented
I think everything is done now!

2022-05-20 22:36 UTC, aristocratos requested changes
As far as I know we can safely assume that the pid of `kthreadd` is always gonna be `2`.

I think a more efficient way to go about this would be to add a:
 `static vector<size_t> kernel_pids = {2}` at the begging of `collect()`.

Then after line 1515 `const size_t pid = stoul(pid_str);`:
 `if (should_filter_kernel and v_contains(kernel_pids, pid)) continue;`

And below 1649 `pread.close();`:
`if (should_filter_kernel and new_proc.ppid == 2) {
	kernel_pids.push_back(new_proc.pid);
	current_procs.erase(rng::find(current_procs, new_proc.pid, &proc_info::pid));
	found.pop_back();
	continue;
}`

That way we aren't constantly adding and removing the kernel processes at every update.
Note that the code above is just an example, I haven't tested it.

2022-05-20 22:36 UTC, aristocratos commented on src/btop_config.cpp
> +// clang-format off
Should be removed.

2022-05-20 22:36 UTC, aristocratos commented on src/btop_menu.cpp
> +// clang-format off
Should be removed.

2022-05-20 22:36 UTC, aristocratos commented on src/linux/btop_collect.cpp
> +// clang-format off
Should be removed.

2022-05-20 22:36 UTC, aristocratos commented on src/btop_menu.cpp
> +                "Removes processes most users don't care about."},
This line is too long to fit in the options box, needs to be split with "about." on a new line.

2022-05-20 22:36 UTC, aristocratos commented on src/btop_menu.cpp
> +                "Filter kernel processes from output",
Should add a (Linux) tag unless you are gonna add support for FreeBSD and macos now also.

2022-05-21 11:21 UTC, 0xJoeMama commented on src/btop_menu.cpp
> +                "Removes processes most users don't care about."},
I am aware of this. I actually implemented a fix locally but didn't have time to push.

2022-05-21 11:24 UTC, 0xJoeMama commented on src/btop_menu.cpp
> +                "Filter kernel processes from output",
I am not sure of how FreeBSD and OSX handle processes so I will keep it Linux only on my part. However, if anyone in the future wishes to add that functionality, they can just go ahead and do so. 

Also, I suppose by '(Linux) tag' you mean added '(Linux)' in the beginning of the line. Correct?

2022-05-21 11:26 UTC, 0xJoeMama commented
> I think a more efficient way to go about this would be to add a...

I agree and I was actually thinking of ways to make this more efficient. However the making sure kthreadd is always pid 2 part is something I wasn't aware of. It is gonna help a lot.

2022-05-21 12:02 UTC, 0xJoeMama commented
I don't think caching would work here since if we cache a kernel process that is restarted with a different id, that would mean any process that acquires the old kernel process id would be filtered out. That is why I just pop back the process vector in my version. Let me know if you have any other ideas.

2022-05-21 13:19 UTC, aristocratos requested changes
I don't think a cache would be an issue, since PIDs are always incrementing a wrap around is very rare considering how high PID_MAX_LIMIT is on most systems. To make sure it doesn't happen you could add a counter that clears out the cache every 100 updates and all should be good.
Will still save alot of cpu by not collecting stats for processes that we will immediately discard.

2022-05-21 13:19 UTC, aristocratos commented on src/linux/btop_collect.cpp
> +					current_procs.pop_back();
`pop_back()` won't work if `should_filter_kernel` is set to true at a later time, since `new_proc` is only guaranteed to be the last added element when it doesn't already exist in `current_procs`. So a search is needed.

You also need a `continue` after `found.pop_back()` else you have operations being done on a dangling reference below.

2022-05-21 14:06 UTC, 0xJoeMama commented on src/linux/btop_collect.cpp
> +					current_procs.pop_back();
> So a search is needed.

Uhm, isn't it the case that a kernel process cannot be in the current_procs list already when we check for it?
Wouldn't it have been already filtered out?

2022-05-21 14:08 UTC, 0xJoeMama commented on src/linux/btop_collect.cpp
> +					current_procs.pop_back();
The dangling reference thing, yeah it's true. I forgot the continue there.

2022-05-21 14:12 UTC, aristocratos commented on src/linux/btop_collect.cpp
> +					current_procs.pop_back();
Not when `should_filter_kernel` is a configurable value that can be toggled at any time in the options.
In the case that the config value is false and then later toggled to true the current code will restart removing the last element every time it finds a kernel process and it's very likely that the last element isn't the process we want and really weird behavior will result.

2022-05-21 14:13 UTC, 0xJoeMama commented on src/linux/btop_collect.cpp
> +					current_procs.pop_back();
However I do agree with the saving of CPU time by skipping calculations. Therefore it seems a cached implementation would improve runtime. However, because of constant access time an unordered_set would be better in my opinion(assuming they are implemented with a backing array and not a linked_list). I will look into an implementation however I have started preparing for an exam, so it's gonna take some time.

2022-05-21 16:42 UTC, aristocratos commented on src/linux/btop_collect.cpp
> +					current_procs.pop_back();
I doubt you'll see much difference considering the size of the cache, but there is `robin_hood::unordered_set` already included you can use.

From https://github.com/martinus/robin-hood-hashing:
> Two memory layouts. Data is either stored in a flat array, or with node indirection. Access for unordered_flat_map is extremely fast due to no indirection, but references to elements are not stable. It also causes allocation spikes when the map resizes, and will need plenty of memory for large objects. Node based map has stable references & pointers (NOT iterators! Similar to [std::unordered_map](https://en.cppreference.com/w/cpp/container/unordered_map)) and uses `const Key` in the pair. It is a bit slower due to indirection. The choice is yours; you can either use `robin_hood::unordered_flat_map` or `robin_hood::unordered_node_map` directly. If you use `robin_hood::unordered_map` It tries to choose the layout that seems appropriate for your data.

2022-05-24 18:48 UTC, 0xJoeMama commented on src/linux/btop_collect.cpp
> +					current_procs.pop_back();
The new changes should handle this case.

2022-05-29 13:12 UTC, 0xJoeMama commented
I think the requested changes are done. Take a look and tell me if you need anything.

2022-06-29 09:11 UTC, merged

2022-06-29 09:29 UTC, aristocratos commented
Merged with some added optimizations.

Thanks for contributing!