Added support for ZFS pool io stats monitoring
aristocratos/btop pull request #374
Opened 2022-06-25 15:33 UTC by simplepad

This pull request adds support for ZFS pool io monitoring, using file `/proc/spl/kstat/zfs/*pool_name*/io`.

Reads and writes are recorded as bytes, not sectors, so there is no need to multiply it by 512.
Since zfs stat collection is different from block device stat collection, `disk` has to store filesystem type to determine which collection method should be used.
Also, `io_ticks` for zfs are recorded separetely for reads and writes, so to get a total I added `io_ticks_read` and `io_ticks_write` variables.

2022-06-27 14:41 UTC, anarcat commented on src/btop_shared.hpp
> +        string fstype;
indentation looks odd here.

2022-06-27 14:42 UTC, anarcat commented
this would be great to have. it's rather surprising to not see ZFS-related disk I/O stats in btop. i would understand we don't have it per dataset, but surely it should be registered in the merged view!

also, it would be nice to have pools instead of dataset in the disk usage listing, does this PR change that?

2022-06-27 16:13 UTC, simplepad commented on src/btop_shared.hpp
> +        string fstype;
thanks for noticing this! fixed

2022-06-27 16:18 UTC, simplepad commented
> also, it would be nice to have pools instead of dataset in the disk usage listing, does this PR change that?
No, this PR is focused only on ZFS pool io monitoring, I didn't alter the listings logic in any way.

2022-06-29 08:47 UTC, aristocratos requested changes
Looks great, other than the requested change, awesome work :)

2022-06-29 11:08 UTC, aristocratos commented on src/linux/btop_collect.cpp
> +						Logger::warning("Error in Mem::collect() : when opening " + (string)disk.stat);
Oh ok. Could just change it to `Logger::debug` instead then, since it could be helpful if IO stats is missing but won't print anything to logfile unless running in debug mode.

2022-06-29 11:43 UTC, simplepad commented on src/linux/btop_collect.cpp
> +						Logger::warning("Error in Mem::collect() : when opening " + (string)disk.stat);
changed to Logger::debug

2022-06-29 11:46 UTC, merged

2022-07-01 06:20 UTC, simplepad commented
That's interesting, perhaps they aren't using it anymore? I was testing Debian Bullseye's last version of zfs-utils, and it had this file. I'll try to look into this, thanks for the report. 
Also, could you please open an issue to track this?