Use fmt for logging and allow to log to system daemon directly
aristocratos/btop pull request #606
Opened 2023-08-29 12:10 UTC by nobounce

This PR improves the logger in a few ways:
1. The logger now lives in it's own file, which avoids unnecessary recompilation
2. The logger uses `fmt`, See #535 
   - The logging functions now have the same syntax as `fmt::format`
   - The logging backend logs with `fmt::print` instead of `std::ofstream`
5. `FMT_HEADER_ONLY` is now defined by Make and passed to the compiler. Other files including `<fmt/*.h>` are now independent of the define in `btop_tools.hpp`
6. By default, if `<syslog.h>` is present, btop will log it's messages there
7. When compiled with `make ENABLE_JOURNALD=true` btop can directly log to journald. This can log interesting metadata like the source file location for each message

On systemd system, with either syslog or journald logging, btops logs can be read with `journalctl -t btop`

If this is not a good default, it's an easy fix to but this behind a `ENABLE_...` flag!
I'm curious if this is a nice feature or not. Looking forward for feedback :)

2023-08-29 20:44 UTC, nobounce commented
Apples `shell` command within make has some kind of issue with line 168, but I'm not sure why

2023-09-10 22:37 UTC, nobounce commented
Fixed the shell issue. You need to escape the `#` in Apples make, which on the other hand doesn't work on Linux... `#` omitted :)

2023-09-13 17:54 UTC, aristocratos commented
@nobounce
Nice work!
I like the idea, but would prefer the defaults to keep the code contained (with only simple logfile logging).
But having the option to easily enable `syslog` or `journald` options would be great.
Don't forget to add documentation in the compile sections of the README.md

2023-09-13 17:55 UTC, aristocratos requested changes
@nobounce
Nice work!
I like the idea, but would prefer the defaults to keep the code contained (with only simple logfile logging).
But having the option to easily enable syslog or journald options would be great.
Don't forget to add documentation in the compile sections of the README.md

2023-09-13 19:16 UTC, nobounce commented
@aristocratos 
I'm on it

2023-09-13 19:55 UTC, nobounce commented
@aristocratos 
Rebased, added the same logic to CMakeLists.txt, changed default back to plain log file and added documentation

2023-09-13 21:32 UTC, nobounce commented
You can actually omit your additional commit (aristocratos Merge PR `#XY` from ZZ) when you merge PR's unless this is done for a reason

2023-09-18 18:24 UTC, nobounce commented
@aristocratos
Rebased, added the same logic to CMakeLists.txt, changed default back to plain log file and added documentation

2023-09-19 11:57 UTC, nobounce commented
@aristocratos
In theory this is good to go

2024-02-20 10:27 UTC, closed without merging