Remove detailed compiler check
aristocratos/btop pull request #613
Opened 2023-09-13 20:24 UTC by nobounce

Currently g++ is forced to be the latest intalled version

Since we give an error if the version of the compiler is not sufficient, we can remove this check/overwrite

It's now possible to specify an older version (on purpose) and new compiler version don't need to be added manually

2023-09-30 17:05 UTC, aristocratos requested changes
I believe I mentioned I was planning to do this (but forgot), so good initiative 👌

2023-09-30 17:05 UTC, aristocratos commented on .github/workflows/continuous-build-freebsd.yml
> -            git config --global --add safe.directory /Users/runner/work/btop/btop
Why is line 43 removed?

From https://github.com/aristocratos/btop/actions/runs/6177943184/job/16770149424?pr=613#step:3:1461

```
  Build complete in (02m:25s)
  fatal: detected dubious ownership in repository at '/Users/runner/work/btop/btop'
  To add an exception for this directory, call:
  
  	git config --global --add safe.directory /Users/runner/work/btop/btop
```

2023-10-01 12:11 UTC, nobounce commented on .github/workflows/continuous-build-freebsd.yml
> -            git config --global --add safe.directory /Users/runner/work/btop/btop
Good catch, again this wasn't supposed to be committed. Fixed it

2024-01-03 14:26 UTC, aristocratos approved these changes

2024-01-03 14:26 UTC, merged

2024-01-03 14:37 UTC, aristocratos commented
@kz6fittycent 
The build for the workflow `test-snap-can-build.yml` fails after this was merged.
I'm guessing the compiler needs to be specified in the build script, I can't however see the actual build command in the workflow, so not sure how to fix it.

2024-01-03 15:10 UTC, aristocratos commented
@kz6fittycent 
Added `CXX=g++-11` to the make flags in https://github.com/aristocratos/btop/blob/main/snap/snapcraft.yaml
And it's working again.