Try get terminal size of "/dev/tty" of stdout fails
aristocratos/btop pull request #627
Opened 2023-09-22 19:04 UTC by nobounce

LLDB does not set the terminal sizes for stdout so try to get them for "/dev/tty". This helps to get back traces on arm64 where gdb is not supported

2023-09-30 17:14 UTC, aristocratos requested changes
Great idea!

But I think this could be reworked to be a bit more efficient.
For example if the deafult `STDOUT_FILENO` fails, setting a bool that switches over to using `/dev/tty` instead.

2023-10-01 12:18 UTC, nobounce commented
@aristocratos


> Great idea!
> 
> But I think this could be reworked to be a bit more efficient. For example if the deafult `STDOUT_FILENO` fails, setting a bool that switches over to using `/dev/tty` instead.

I can't quite follow what you mean by that. Currently it is checked if `STDOUT_FILENO` can be used to get valid terminal dimensions, if it's not the case it tries to fall back to `/dev/tty` ...

Where would the bool come into play?

2023-10-01 12:33 UTC, aristocratos commented
> Where would the bool come into play?

`Term::refresh` is called at a minimum once every update cycle, since [SIGWINCH](https://www.gnu.org/software/libc/manual/html_node/Miscellaneous-Signals.html#index-SIGWINCH) isn't always reliable.
So if we are running on a system where `STDOUT_FILENO` fails to get current size, we will continue to make that same syscall every time we run `Term::refresh` even though it's gonna fail every time.

Syscalls cost a lot more than branching.

2024-01-03 15:39 UTC, aristocratos approved these changes

2024-01-03 15:40 UTC, merged