[fix] Made disks statvfs logic asynchronous.
aristocratos/btop pull request #633
Opened 2023-09-27 19:41 UTC by crestfallnatwork

Fixes #632 

Read the following comment to get the full context of the problem: 
* [Comment](https://github.com/aristocratos/btop/issues/392#issuecomment-1719056607)  

This pull request mostly follows the solution described in the following comment:
* [Comment](https://github.com/aristocratos/btop/issues/392#issuecomment-1722193694)

2023-09-27 20:35 UTC, aristocratos requested changes
See requested change.
Otherwise nice work!

2023-09-27 20:35 UTC, aristocratos commented on src/linux/btop_collect.cpp
> +						disk = promise_res.first;
`disk = promise_res.first;` will write over any IO stats collected later in this same section.
Since we are passing a copy of the `disk_info` struct in to the lambda.

Needs to be changed to update `disk.total`, `disk.free`, etc. instead.

2023-09-27 22:53 UTC, crestfallnatwork commented on src/linux/btop_collect.cpp
> +						disk = promise_res.first;
My bad. Didn't notice that we used the same struct to get IO stats as well. 
But even if we just update the fields of the disk_info struct, wouldn't this still cause problems as we try to access discs that may fail statvfs later?
Should I add something like a ready flag to indicate if the disk in question has passed statvfs? 
But this would cause disk IO stats to take at least 2 cycles to update.

2023-09-28 09:19 UTC, aristocratos commented on src/linux/btop_collect.cpp
> +						disk = promise_res.first;
> But even if we just update the fields of the disk_info struct, wouldn't this still cause problems as we try to access discs that may fail statvfs later?
Should I add something like a ready flag to indicate if the disk in question has passed statvfs?

The `access(disk.stat.c_str(), R_OK) != 0)` check at the start of the IO collection should be enough i think, since we're "just" reading files from `/sys/`, they either exists or don't, so shouldn't be any issue.

But maybe there should be a higher level ignore list, for disks that keeps getting added when detecting disks but continuously fails `statvfs`, so they get ignored for good after X amount of tries.

2023-09-28 09:41 UTC, nobounce commented
Please don't fix issues in a second commit.
You can squash both commits by running something like
```
git reset --soft HEAD^
git commit --all --amend --no-edit
git push -f
```

2023-09-29 03:19 UTC, crestfallnatwork commented on src/linux/btop_collect.cpp
> +						disk = promise_res.first;
Point noted. The `is_ready` check is almost certainly useless.
The current ignore list is most probably sufficient if something fails `statvfs`, it is most likely to keep failing `statvfs`.

2023-09-29 07:52 UTC, aristocratos approved these changes

2023-09-29 08:43 UTC, aristocratos commented
Nice work @crestfallnatwork, merging in to main, hopefully this also solves #392 and possibly other issues where the cause of issue is unknown.

2023-09-29 08:43 UTC, merged