Refresh rate
aristocratos/btop pull request #640
Opened 2023-10-03 12:02 UTC by nobounce

Closes: #551

2023-11-15 20:40 UTC, aristocratos requested changes

2023-11-15 20:40 UTC, aristocratos commented on src/btop.cpp
> +					"  -r, --refresh <ms>    set the refresh rate in milliseconds\n"
Would you mind changing `-r` to `-u` and `refresh rate` to `program update rate`, to keep it consistent between how it's named in the config?

2024-01-03 16:17 UTC, aristocratos requested changes

2024-01-03 16:17 UTC, aristocratos commented on src/btop.cpp
> +					"usage: btop [-h] [-v] [-/+t] [-p <id>] [-r <ms>] [--utf-force] [--debug]\n\n"
`-u <ms>`

2024-01-03 16:17 UTC, aristocratos commented on src/btop.cpp
> +					"  -u, --refresh <ms>    set the program update rate in milliseconds\n"
Should probably be `-u, --update <ms>` to be more consistent.

2024-01-03 16:17 UTC, aristocratos commented on src/btop.cpp
> +				exit(1);
refresh -> update

2024-01-03 16:21 UTC, aristocratos commented on src/btop.cpp
> +				Global::arg_refresh = std::clamp(std::stoi(value), 100, 99999);
The current max value from config is `86400000`

See https://github.com/aristocratos/btop/blob/f6cab3d3bdc06bec91c5b3681fbb2f00418e17ef/src/btop_config.cpp#L492

2024-01-03 16:26 UTC, imwints commented on src/btop.cpp
> +				Global::arg_refresh = std::clamp(std::stoi(value), 100, 99999);
Should we give this value a name?

2024-01-03 16:29 UTC, aristocratos commented on src/btop.cpp
> +				Global::arg_refresh = std::clamp(std::stoi(value), 100, 99999);
Well it's equal to 1 day in ms, so could be written as `1000 * 60 * 60 * 24` to make it more clear.

2024-01-03 16:31 UTC, imwints commented on src/btop.cpp
> +				Global::arg_refresh = std::clamp(std::stoi(value), 100, 99999);
I think the most readable approach would be to make an named constant like `constexpr int ONE_DAY_MILLIS = 1000 * 60 * 60 * 24;` in Config

2024-01-03 16:34 UTC, aristocratos commented on src/btop.cpp
> +				Global::arg_refresh = std::clamp(std::stoi(value), 100, 99999);
Sure.

2024-01-03 16:43 UTC, aristocratos approved these changes

2024-01-03 16:43 UTC, merged